version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: ">=15.0.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
